# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: IO.GT MAIN SITE
    url: https://io.gt
  - name: Client Area
    url: https://clientarea.io.gt
  - name: PBX System 1
    url: $PBX_IOGT
  - name: PBX System 2
    url: $PBX2_IOGT
  - name: PBX System Dev
    url: $PBX3_IOGT
  - name: IOGT HOSTING
    url: $IOGT_CPANEL
  - name: IO.GT DNS 1
    check: "tcp-ping"
    url: dns1.io.gt
    port: 53
  - name: IO.GT DNS 1
    check: "tcp-ping"
    url: dns1.io.gt
    port: 53
  - name: IO.GT DNS 2
    check: "tcp-ping"
    url: dns2.io.gt
    port: 53
  - name: IO.GT DNS 3
    check: "tcp-ping"
    url: dns3.io.gt
    port: 53
  - name: IO.GT DNS 4
    check: "tcp-ping"
    url: dns4.io.gt
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.io.gt
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: IO.GT Status Page
  introTitle: "**IO.GT** systems status page."
  introMessage: This is a page to monitor all IO.GT systems status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
